# Site settings
title: CMSC498T (Spring 2015)
email: hcorrada@umiacs.umd.edu
description: "CMSC498T, Introduction to Data Science II: Exploring, modeling and communicating with data"
baseurl: "/IntroDataSci"
twitter_username: hcorrada
github_username:  hcorrada
ignore: ["materials", "tasks"]

pageOrder: ["/index.html", "/calendar.html","/resources.html","/syllabus.html","/projects.html"]

# Build settings
markdown: kramdown
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# my variables
piazza_url: "https://piazza.com/class/i5e39xpjr662in"
elms_url: "https://myelms.umd.edu/courses/1130499"

